/* Sweat & Stats v2.4.0.2.1 correction patch */
(() => {
'use strict';
const PATCH_VERSION='2.4.0.2.1';
const $p=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').trim().replace(/\s+/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const uid=()=>crypto.randomUUID?.()||`id-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const readJSON=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}};
const writeJSON=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const nowISO=()=>new Date().toISOString();
const SCHEMA=241;
const CLOUD_KEYS=['sw2_custom_equipment_names','sw2_library','sw2_today','sw2_plans','sw2_history','sw2_notes','sw2_custom_equipment_names','sw2_custom_equipment_types','sw2_custom_muscles','sw2_schema_version','sw2_profile','sw2_profile_name','sw2_running','sw2_start','sw2_elapsed','sw2_sync_state'];
let customEquipmentTypes=readJSON('sw2_custom_equipment_types',[]);
let customMuscles=readJSON('sw2_custom_muscles',[]);
let selectedMood='';
let completionRecord=null;
let importDraft=[];
let cloud={user:null,db:null,auth:null,loading:false,timer:null};

function migrate(){
 const current=Number(localStorage.getItem('sw2_schema_version')||0);
 if(current>=SCHEMA)return;
 const backup={createdAt:nowISO(),schemaVersion:current,data:{}};
 for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k?.startsWith('sw2_'))backup.data[k]=localStorage.getItem(k)}
 localStorage.setItem(`sw2_backup_${Date.now()}`,JSON.stringify(backup));
 try{
  library=(Array.isArray(library)?library:[]).map(e=>({...e,id:e.id||uid(),secondaryGroup:e.secondaryGroup||'',secondaryType:e.secondaryType||''}));
  const builtins=[
   {name:'Donkey Kick (Mat)',primaryGroup:'Glutes',primaryType:'Glutes',secondaryGroup:'Legs',secondaryType:'Hamstrings',movement:'Hip Extension',equipmentName:'Exercise Mat',equipmentType:'Mat'},
   {name:'Donkey Kick (Machine)',primaryGroup:'Glutes',primaryType:'Glutes',secondaryGroup:'Legs',secondaryType:'Hamstrings',movement:'Hip Extension',equipmentName:'Glute Kickback Machine',equipmentType:'Selectorized Weight Machine'}
  ];
  for(const b of builtins)if(!library.some(e=>e.name?.toLowerCase()===b.name.toLowerCase()))library.push({id:uid(),...b,...defaults(false)});
  const hist=readJSON('sw2_history',[]).map(w=>({...w,id:w.id||uid(),date:w.date||nowISO(),exercises:(w.exercises||[]).map(e=>({...e,id:e.id||library.find(x=>x.name===e.name)?.id||uid()}))}));
  writeJSON('sw2_history',hist); writeJSON('sw2_library',library);
  localStorage.setItem('sw2_schema_version',String(SCHEMA));
 }catch(err){console.error('Migration failed',err);alert('Data migration could not finish. A recoverable backup was preserved.');}
}

function allEquipmentTypes(){
 const base=[...new Set([...EQUIPMENT_TYPES.filter(x=>x!=='Other'),'Mat','Bench'])];
 for(const x of customEquipmentTypes)if(!base.some(b=>b.toLowerCase()===x.toLowerCase()))base.push(x);
 return [...base,'Other / Add New'];
}
function allGroups(){return [...new Set([...MUSCLE_GROUPS,...customMuscles.map(x=>x.group)])].filter(Boolean)}
function allTypes(group){return [...new Set([...(MUSCLE_TYPES[group]||[]),...customMuscles.filter(x=>x.group===group).map(x=>x.type)])]}
function saveCustomEquipment(raw){const v=norm(raw);if(!v)return'';const existing=[...allEquipmentTypes()].find(x=>x.toLowerCase()===v.toLowerCase());if(existing&&existing!=='Other / Add New')return existing;customEquipmentTypes.push(v);customEquipmentTypes=[...new Map(customEquipmentTypes.map(x=>[x.toLowerCase(),x])).values()];writeJSON('sw2_custom_equipment_types',customEquipmentTypes);queueCloudSync();return v}
function saveCustomMuscle(group,type){group=norm(group);type=norm(type);if(!group||!type)return null;const found=customMuscles.find(x=>x.group.toLowerCase()===group.toLowerCase()&&x.type.toLowerCase()===type.toLowerCase());if(found)return found;const item={group,type};customMuscles.push(item);writeJSON('sw2_custom_muscles',customMuscles);queueCloudSync();return item}

function historyNewest(){return getHistory().slice().sort((a,b)=>new Date(b.date)-new Date(a.date))}
function latestPerformance(ex){
 for(const w of historyNewest()){
  const hit=(w.exercises||[]).find(x=>(ex.id&&x.id===ex.id)||x.name?.toLowerCase()===ex.name?.toLowerCase());
  if(hit)return{workout:w,exercise:hit};
 }
 return null;
}
function cleanToday(ex,{preload=true}={}){
 const base={...clone(ex),done:false,effort:'',note:''};
 const last=preload?latestPerformance(ex):null;
 if(last){
  if(base.kind==='cardio'){base.minutes=last.exercise.minutes??base.minutes;base.floors=last.exercise.floors??base.floors}
  else base.sets=clone(last.exercise.sets||base.sets||[]);
 }
 return base;
}
function exerciseCurrent(ex){
 if(ex.kind==='cardio')return `${Number(ex.minutes)||0} min${ex.floors!==''&&ex.floors!=null?`, ${Number(ex.floors)||0} floors`:''}`;
 const sets=ex.sets||[]; if(!sets.length)return'No sets';
 const same=sets.every(s=>String(s.reps)===String(sets[0].reps)&&String(s.weight)===String(sets[0].weight));
 if(same)return `${sets.length} × ${sets[0].reps||0}${sets[0].weight!==''?` @ ${sets[0].weight} lb`:''}`;
 return sets.map(s=>`${s.reps||0}${s.weight!==''?` @ ${s.weight} lb`:''}`).join(', ');
}
function performanceHTML(ex){const p=latestPerformance(ex);if(!p)return'';const d=new Date(p.workout.date).toLocaleDateString(undefined,{year:'numeric',month:'long',day:'numeric'});return `<div class="previous-performance"><b>Last: ${esc(d)}</b><div>${esc(exerciseCurrent(p.exercise))}</div>${p.exercise.effort?`<div>Effort: ${esc(p.exercise.effort)}</div>`:''}${p.exercise.note?`<div>Note: ${esc(p.exercise.note)}</div>`:''}</div>`}

function persistPatched(){
 localStorage.setItem('sw2_library',JSON.stringify(library));localStorage.setItem('sw2_today',JSON.stringify(exercises));localStorage.setItem('sw2_plans',JSON.stringify(plans));localStorage.setItem('sw2_running',running);localStorage.setItem('sw2_start',start||'');localStorage.setItem('sw2_elapsed',elapsed);localStorage.setItem('sw2_notes',$p('workoutNotes')?.value||'');
 queueCloudSync();
}
persist=persistPatched;

renderToday=function(){
 const list=$p('exerciseList'); if(!list)return;
 list.innerHTML=exercises.length?'':"<div class='card empty'>No exercises added yet.</div>";
 exercises.forEach((ex,i)=>{
  const d=document.createElement('div');d.className=`card active-exercise ${ex.done?'exercise-complete':''}`;
  const sets=ex.kind==='cardio'?`<div class="grid2"><div class="field"><label>Minutes</label><input value="${esc(ex.minutes??'')}" oninput="updateCardio(${i},'minutes',this.value)"></div><div class="field"><label>Floors</label><input value="${esc(ex.floors??'')}" oninput="updateCardio(${i},'floors',this.value)"></div></div>`:`${(ex.sets||[]).map((s,j)=>`<div class="set-row"><b>${j+1}</b><div class="field"><label>Reps</label><input value="${esc(s.reps??'')}" oninput="updateSet(${i},${j},'reps',this.value)"></div><div class="field"><label>Weight</label><input value="${esc(s.weight??'')}" oninput="updateSet(${i},${j},'weight',this.value)"></div><button class="btn danger" onclick="removeSet(${i},${j})">×</button></div>`).join('')}<button class="btn ghost full" onclick="addSet(${i})">+ Add Different Set</button>`;
  d.innerHTML=`<div class="exercise-head"><div><div class="exercise-name">${esc(ex.name)} ${ex.done?'<span class="complete-badge">✓ Completed</span>':''}</div><div class="chips">${detailChips(ex)}</div></div><div class="actions"><button class="btn ghost" onclick="moveEx(${i},-1)">↑</button><button class="btn ghost" onclick="moveEx(${i},1)">↓</button></div></div>${performanceHTML(ex)}<div class="current-summary"><b>Current:</b> <span id="current-${i}">${esc(exerciseCurrent(ex))}</span></div>${sets}<div class="grid2" style="margin-top:8px"><div class="field"><label>Effort</label><select onchange="updateMeta(${i},'effort',this.value)"><option></option>${['Easy','Moderate','Hard','Struggle'].map(v=>`<option ${ex.effort===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>Exercise Note</label><input value="${esc(ex.note||'')}" oninput="updateMeta(${i},'note',this.value)"></div></div><div class="actions" style="margin-top:8px"><button class="btn ${ex.done?'complete-action':'primary'}" style="flex:1" onclick="toggleDone(${i})">${ex.done?'Completed ✓':'Mark Complete'}</button><button class="btn danger" onclick="removeExercise(${i})">Remove</button></div>`;
  list.appendChild(d);
 });
 renderDashboard();
};
window.updateSet=(i,j,k,v)=>{exercises[i].sets[j][k]=v;const x=$p(`current-${i}`);if(x)x.textContent=exerciseCurrent(exercises[i]);persist()};
window.updateCardio=(i,k,v)=>{exercises[i][k]=v;const x=$p(`current-${i}`);if(x)x.textContent=exerciseCurrent(exercises[i]);persist()};
window.updateMeta=(i,k,v)=>{exercises[i][k]=v;persist()};
window.addSet=i=>{exercises[i].sets.push(clone(exercises[i].sets.at(-1)||{reps:10,weight:''}));renderToday();persist()};
window.removeSet=(i,j)=>{if(exercises[i].sets.length>1)exercises[i].sets.splice(j,1);renderToday();persist()};
window.toggleDone=i=>{exercises[i].done=!exercises[i].done;renderToday();persist()};
window.removeExercise=i=>{exercises.splice(i,1);renderToday();persist()};
window.addNamed=id=>{const ex=library.find(x=>x.id===id);if(ex){exercises.push(cleanToday(ex));renderToday();persist();showPage('today')}};

function statsForExercises(items){let sets=0,reps=0,volume=0,cardio=0,floors=0;const muscles=new Set();for(const ex of items){muscles.add(ex.primaryGroup);if(ex.secondaryGroup)muscles.add(ex.secondaryGroup);if(ex.kind==='cardio'){cardio+=Number(ex.minutes)||0;floors+=Number(ex.floors)||0}else for(const s of ex.sets||[]){sets++;reps+=Number(s.reps)||0;if(Number(s.weight)>0)volume+=(Number(s.reps)||0)*Number(s.weight)}}return{sets,reps,volume,cardio,floors,muscles:[...muscles]}}
function workoutSummary(record){const st=statsForExercises(record.exercises||[]);let lines=[`Workout: ${record.title||'Completed Workout'}`,`Workout — ${new Date(record.date||Date.now()).toLocaleDateString()}`,`${Math.round((record.duration||0)/60000)} min`,''];for(const ex of record.exercises||[]){lines.push(`✔ ${ex.name}: ${exerciseCurrent(ex)}`);if(ex.effort)lines.push(`  Effort: ${ex.effort}`);if(ex.note)lines.push(`  Note: ${ex.note}`)}if(record.mood)lines.push('',`Mood: ${record.mood}`);if(record.notes)lines.push('',`Workout Notes: ${record.notes}`);lines.push('',`Completed exercises: ${(record.exercises||[]).length}`,`Total sets: ${st.sets}`,`Total reps: ${st.reps}`,`Total volume: ${Math.round(st.volume)} lb`,`Muscles trained: ${st.muscles.join(', ')||'None'}`);return lines.join('\n')}
buildSummary=function(){return workoutSummary({title:localStorage.getItem('sw2_workout_title')||"Today's Workout",date:nowISO(),duration:elapsedNow(),exercises:exercises.filter(x=>x.done),notes:$p('workoutNotes').value,mood:selectedMood})};

function openComplete(){
 const done=exercises.filter(x=>x.done);if(!done.length)return alert('Complete at least one exercise before finishing.');pauseTimer();const st=statsForExercises(done);completionRecord={id:uid(),title:localStorage.getItem('sw2_workout_title')||'Workout',date:nowISO(),duration:elapsedNow(),exercises:clone(done),notes:$p('workoutNotes').value,mood:''};
 $p('completionStats').innerHTML=`<div class="history-stat"><b>${Math.round(completionRecord.duration/60000)}</b><span>Minutes</span></div><div class="history-stat"><b>${done.length}</b><span>Exercises</span></div><div class="history-stat"><b>${st.sets}</b><span>Sets</span></div><div class="history-stat"><b>${st.reps}</b><span>Reps</span></div><div class="history-stat"><b>${Math.round(st.volume).toLocaleString()}</b><span>Volume lb</span></div>`;
 $p('completionMuscles').textContent=st.muscles.join(' · ')||'No muscle data';
 $p('completionNotes').value=completionRecord.notes||''; selectedMood='';
 $p('completionMood').innerHTML=['Great','Good','Okay','Low Energy','Wanted to Leave'].map(m=>`<button class="btn mood-btn" data-mood="${m}">${m}</button>`).join('');
 $p('completionMood').querySelectorAll('button').forEach(b=>b.onclick=()=>{selectedMood=b.dataset.mood;$p('completionMood').querySelectorAll('button').forEach(x=>x.classList.toggle('primary',x===b))});
 document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));$p('workoutCompleteScreen').classList.add('active');window.scrollTo(0,0);
}
function finalSave(){
 if(!completionRecord)return;completionRecord.notes=$p('completionNotes').value.trim();completionRecord.mood=selectedMood;const st=statsForExercises(completionRecord.exercises);Object.assign(completionRecord,{completedExercises:completionRecord.exercises.length,totalSets:st.sets,totalReps:st.reps,totalVolume:st.volume,muscles:st.muscles,cardioMinutes:st.cardio,floors:st.floors});
 const hist=getHistory();if(hist.some(w=>w.id===completionRecord.id))return alert('This workout was already saved.');hist.push(completionRecord);writeJSON('sw2_history',hist);const saved=clone(completionRecord);
 exercises=[];elapsed=0;running=false;start=null;clearInterval(interval);$p('workoutNotes').value='';localStorage.removeItem('sw2_workout_title');selectedMood='';completionRecord=null;persist();tick();renderToday();renderHistory();renderDashboard();
 showPostSave(saved);
}
function showPostSave(w){const dlg=$p('postSaveDialog');dlg.dataset.id=w.id;$p('postSaveText').textContent='Workout saved successfully.';dlg.showModal()}

function repeatWorkout(w){if(exercises.length&&!confirm('Replace the active workout?'))return;exercises=(w.exercises||[]).map(ex=>cleanToday({...ex,effort:'',note:'',done:false},{preload:false}));localStorage.setItem('sw2_workout_title',`Repeat: ${w.title||new Date(w.date).toLocaleDateString()}`);elapsed=0;running=false;start=null;$p('workoutNotes').value='';persist();renderToday();showPage('today')}
function repeatPrevious(){const w=historyNewest()[0];if(!w)return alert('No completed workout is available to repeat.');repeatWorkout(w)}

function parseWorkoutTextPatched(text){let title='',overall='',loaded=[],current=null;for(const raw of text.split(/\r?\n/)){let line=raw.trim();if(!line)continue;let tm=line.match(/^Workout(?: Title)?:\s*(.+)$/i);if(tm){title=tm[1];continue}let wm=line.match(/^Workout Notes?:\s*(.+)$/i);if(wm){overall=wm[1];continue}line=line.replace(/^✔\s*/,'');const match=library.slice().sort((a,b)=>b.name.length-a.name.length).find(x=>line.toLowerCase().includes(x.name.toLowerCase()));if(match){current=cleanToday(match,{preload:false});loaded.push(current);const cm=line.match(/(\d+)\s*min(?:,\s*(\d+)\s*floors?)?/i);if(cm&&current.kind==='cardio'){current.minutes=+cm[1];current.floors=cm[2]?+cm[2]:''}const all=[...line.matchAll(/(\d+)\s*[x×]\s*(\d+)\s*@\s*([\d.]+)\s*lb?/gi)];if(all.length&&current.kind!=='cardio')current.sets=all.flatMap(m=>Array.from({length:+m[1]},()=>({reps:+m[2],weight:+m[3]})));else if(current.kind!=='cardio'){const plain=[...line.matchAll(/(?:^|,\s*)(\d+)\s*@\s*([\d.]+)\s*lb?/gi)];if(plain.length)current.sets=plain.map(m=>({reps:+m[1],weight:+m[2]}))}continue}if(current){let e=line.match(/^Effort:\s*(.+)/i);if(e)current.previousEffort=e[1];let n=line.match(/^Note:\s*(.+)/i);if(n)current.previousNote=n[1]}}
 return{title,overall,loaded};
}
parseWorkoutText=function(text){return parseWorkoutTextPatched(text).loaded};

function balanceGenerate(){
 const focus=$p('randomFocus').value,equip=$p('randomEquipment').value,diff=$p('randomDifficulty').value,count=+$p('randomCount').value,dur=+$p('randomDuration').value;const custom=[...$p('randomMuscles').selectedOptions].map(o=>o.value);const map={'Upper Body':['Chest','Back','Shoulders','Biceps','Triceps','Arms'],'Lower Body':['Quads','Hamstrings','Glutes','Hips','Calves','Legs'],'Push':['Chest','Shoulders','Triceps','Quads'],'Pull':['Back','Biceps','Hamstrings'],'Legs':['Quads','Hamstrings','Glutes','Hips','Calves','Legs'],'Core':['Core'],'Cardio':['Cardio'],'Full Body':allGroups()};let groups=focus==='Custom'?custom:(map[focus]||allGroups());if(!groups.length)return alert('Select at least one muscle group.');let pool=library.filter(x=>groups.includes(x.primaryGroup));if(equip!=='Any')pool=pool.filter(x=>equip==='Machines'?x.equipmentType?.includes('Machine'):equip==='Cable'?x.equipmentType==='Cable Machine':equip==='Dumbbells'?x.equipmentType==='Dumbbell':equip==='Bodyweight'?x.equipmentType==='Bodyweight':['Mat','Bench'].includes(equip)?x.equipmentType===equip:true);if(!pool.length)return alert('No exercises match those filters.');
 const buckets=new Map(groups.map(g=>[g,pool.filter(x=>x.primaryGroup===g)]));const chosen=[],patterns=new Map();let guard=0;while(chosen.length<count&&guard++<500){for(const g of groups){const options=(buckets.get(g)||[]).filter(x=>!chosen.some(c=>c.id===x.id)).sort(()=>Math.random()-.5);let pick=options.find(x=>(patterns.get(x.movement)||0)<1)||options[0];if(pick){chosen.push(cleanToday(pick));patterns.set(pick.movement,(patterns.get(pick.movement)||0)+1);if(chosen.length>=count)break}}if(![...buckets.values()].some(arr=>arr.some(x=>!chosen.some(c=>c.id===x.id))))break}
 const sets=diff==='Beginner'?2:diff==='Advanced'?4:3,reps=diff==='Beginner'?10:diff==='Advanced'?15:12;for(const ex of chosen){if(ex.kind==='cardio'&&!latestPerformance(ex))ex.minutes=Math.max(5,Math.round(dur/Math.max(1,chosen.filter(x=>x.kind==='cardio').length)));if(ex.kind!=='cardio'&&!latestPerformance(ex))ex.sets=Array.from({length:sets},()=>({reps,weight:ex.sets?.[0]?.weight||''}))}
 if(!confirmReplace())return;exercises=chosen;localStorage.setItem('sw2_workout_title',focus==='Custom'?`${groups.join(' & ')} Workout`:`${focus} ${diff} Workout`);persist();renderToday();$p('randomWorkoutDialog').close();showPage('today');
}
generateRandom=balanceGenerate;

function renderLibraryPatched(){let q=$p('librarySearch').value.toLowerCase(),g=$p('groupFilter').value,s=$p('librarySort').value;let f=library.filter(x=>(!g||x.primaryGroup===g)&&(!q||JSON.stringify(x).toLowerCase().includes(q)));f.sort((a,b)=>(s==='group'?a.primaryGroup:s==='equipment'?a.equipmentType:a.name).localeCompare(s==='group'?b.primaryGroup:s==='equipment'?b.equipmentType:b.name));$p('libraryList').innerHTML='';for(const ex of f){let d=document.createElement('div');d.className='card';d.innerHTML=`<div class="exercise-head"><div><div class="exercise-name">${esc(ex.name)}</div><div class="chips">${detailChips(ex)}</div><div class="small muted" style="margin-top:6px">${esc(ex.equipmentName)}</div></div><div class="actions library-actions"><button class="btn secondary" onclick="addNamed('${ex.id}')">Add</button><button class="btn ghost" onclick="editExercise('${ex.id}')">Edit</button><button class="btn ghost" onclick="duplicateExercise('${ex.id}')">Duplicate</button><button class="btn ghost" onclick="copyStructuredExercise('${ex.id}')">Copy</button><button class="btn ghost" onclick="openExerciseInsights('${ex.id}')">History</button><button class="btn danger" onclick="deleteExercise('${ex.id}')">Delete</button></div></div>`;$p('libraryList').appendChild(d)}fillAddSelect()}
renderLibrary=renderLibraryPatched;
window.duplicateExercise=id=>{const ex=library.find(x=>x.id===id);if(!ex)return;const copy={...clone(ex),id:'',name:`${ex.name} Copy`};openExercise(copy)};
window.copyStructuredExercise=async id=>{const e=library.find(x=>x.id===id);if(!e)return;const t=`Exercise: ${e.name}\nPrimary Group: ${e.primaryGroup}\nPrimary Type: ${e.primaryType}\nSecondary Group: ${e.secondaryGroup||'None'}\nSecondary Type: ${e.secondaryType||'None'}\nMovement Pattern: ${e.movement}\nEquipment Name: ${e.equipmentName}\nEquipment Type: ${e.equipmentType}`;await navigator.clipboard?.writeText(t);alert('Structured exercise copied.')};
window.openExerciseInsights=id=>{const ex=library.find(x=>x.id===id);if(!ex)return;const rows=[];for(const w of historyNewest()){for(const x of w.exercises||[])if(x.id===id||x.name?.toLowerCase()===ex.name.toLowerCase())rows.push({w,x})}const totalSets=rows.reduce((n,r)=>n+(r.x.sets?.length||0),0),max=Math.max(0,...rows.flatMap(r=>r.x.sets||[]).map(s=>Number(s.weight)||0));$p('exerciseHistoryTitle242').textContent=`${ex.name} History`;$p('exerciseHistoryBody242').innerHTML=`<div class="history-insights"><div class="history-stat"><b>${rows.length}</b><span>Sessions</span></div><div class="history-stat"><b>${totalSets}</b><span>Total Sets</span></div><div class="history-stat"><b>${max}</b><span>Max Weight</span></div></div>${rows.length>1?`<div class="card"><b>Progress Insight</b><div>${(()=>{const a=Math.max(0,...(rows[0].x.sets||[]).map(s=>Number(s.weight)||0)),b=Math.max(0,...(rows[1].x.sets||[]).map(s=>Number(s.weight)||0));return a>b?`Maximum weight increased by ${a-b} lb since the previous session.`:a<b?`Maximum weight is ${b-a} lb below the previous session.`:'Maximum weight is holding steady.'})()}</div></div>`:''}${rows.length?rows.map(r=>`<div class="card"><b>${new Date(r.w.date).toLocaleDateString()}</b><div>${esc(exerciseCurrent(r.x))}</div>${r.x.effort?`<div>Effort: ${esc(r.x.effort)}</div>`:''}${r.x.note?`<div>Note: ${esc(r.x.note)}</div>`:''}</div>`).join(''):'<div class="empty">No completed sessions yet.</div>'}`;$p('exerciseHistoryDialog242').showModal()};

function configureExerciseForm(){
 fillSelect($p('editPrimaryGroup'),allGroups());fillSelect($p('editSecondaryGroup'),allGroups(),'None');fillSelect($p('groupFilter'),allGroups(),'All Groups');
 $p('editEquipmentType').innerHTML=allEquipmentTypes().map(x=>`<option>${esc(x)}</option>`).join('');
 if(!$p('customEquipmentField')){$p('editEquipmentType').closest('.field').insertAdjacentHTML('afterend','<div class="field hidden" id="customEquipmentField"><label>New Equipment Type</label><input id="customEquipmentType" placeholder="Enter reusable type"></div>')}
 $p('editEquipmentType').onchange=()=>{$p('customEquipmentField').classList.toggle('hidden',$p('editEquipmentType').value!=='Other / Add New')};
 if(!$p('namingGuidance2421'))$p('exerciseForm').querySelector('.actions').insertAdjacentHTML('beforebegin','<div id="namingGuidance2421" class="small muted">Naming: use (Mat), (Bench), or (Machine) when the suffix distinguishes the exercise. Do not repeat equipment already in the exercise name.</div>');if(!$p('customMuscleControls')){$p('exerciseForm').querySelector('.actions').insertAdjacentHTML('beforebegin','<details id="customMuscleControls"><summary>Add custom muscle value</summary><div class="grid2"><div class="field"><label>Group</label><input id="newMuscleGroup"></div><div class="field"><label>Type</label><input id="newMuscleType"></div></div><button type="button" class="btn secondary" id="saveCustomMuscleBtn">Add Muscle Value</button></details>');$p('saveCustomMuscleBtn').onclick=()=>{const m=saveCustomMuscle($p('newMuscleGroup').value,$p('newMuscleType').value);if(m){configureExerciseForm();$p('editPrimaryGroup').value=m.group;syncTypesPatched($p('editPrimaryGroup'),$p('editPrimaryType'),m.type)}}}
}
function syncTypesPatched(g,t,current=''){fillSelect(t,allTypes(g.value),'None');if(current)t.value=current}
syncTypes=syncTypesPatched;
const originalOpenExercise=openExercise;
openExercise=function(ex=null){configureExerciseForm();originalOpenExercise(ex);if(ex?.equipmentType)$p('editEquipmentType').value=ex.equipmentType;$p('customEquipmentField').classList.add('hidden')};
$p('exerciseForm').onsubmit=e=>{e.preventDefault();let type=$p('editEquipmentType').value;if(type==='Other / Add New'){type=saveCustomEquipment($p('customEquipmentType').value);if(!type)return alert('Enter a new equipment type.')}const eqName=$p('editEquipmentName').value.trim();if(eqName){let names=readJSON('sw2_custom_equipment_names',[]);if(!names.some(x=>x.toLowerCase()===eqName.toLowerCase())){names.push(eqName);writeJSON('sw2_custom_equipment_names',names)}}let id=$p('editId').value||uid(),old=library.find(x=>x.id===id),data={id,name:$p('editName').value.trim(),primaryGroup:$p('editPrimaryGroup').value,primaryType:$p('editPrimaryType').value,secondaryGroup:$p('editSecondaryGroup').value,secondaryType:$p('editSecondaryType').value,movement:$p('editMovement').value,equipmentName:eqName,equipmentType:type,...defaults($p('editPrimaryGroup').value==='Cardio')};if(old)Object.assign(data,{sets:old.sets,kind:old.kind,minutes:old.minutes,floors:old.floors});let idx=library.findIndex(x=>x.id===id);if(idx>=0)library[idx]=data;else library.push(data);$p('exerciseDialog').close();renderLibrary();persist()};

function validateCandidate(c){const errors=[];for(const k of ['name','primaryGroup','primaryType','movement','equipmentType'])if(!c[k])errors.push(`${k} is required`);return errors}
function renderImportReview(){
 const host=$p('importReviewList242');host.innerHTML=importDraft.map((c,i)=>`<div class="card import-candidate" data-i="${i}"><div class="actions"><label><input type="checkbox" data-field="include" ${c.include!==false?'checked':''}> Include</label><button class="btn danger" data-remove="${i}">Remove</button></div><div class="grid2">${[['name','Exercise'],['primaryGroup','Primary Group'],['primaryType','Primary Type'],['secondaryGroup','Secondary Group'],['secondaryType','Secondary Type'],['movement','Movement Pattern'],['equipmentName','Equipment Name'],['equipmentType','Equipment Type']].map(([k,l])=>`<div class="field"><label>${l}</label><input data-field="${k}" value="${esc(c[k]||'')}"></div>`).join('')}</div><div class="field"><label>Duplicate Resolution</label><select data-field="duplicateChoice"><option>Skip</option><option>Update Existing</option><option>Create New (Rename)</option></select></div><div class="validation ${validateCandidate(c).length?'error-text':'success-text'}">${validateCandidate(c).join(' · ')||'Ready to import'}</div></div>`).join('')||'<div class="empty">Nothing recognized.</div>';
 host.querySelectorAll('[data-field]').forEach(el=>el.oninput=()=>{const i=+el.closest('[data-i]').dataset.i;importDraft[i][el.dataset.field]=el.type==='checkbox'?el.checked:el.value;el.closest('.import-candidate').querySelector('.validation').textContent=validateCandidate(importDraft[i]).join(' · ')||'Ready to import'});host.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{importDraft.splice(+b.dataset.remove,1);renderImportReview()});$p('importReviewDialog242').showModal();
}
previewExerciseImports=function(){importDraft=parseExerciseBlocks($p('exerciseImportText').value).map(c=>({...c,include:true,duplicateChoice:'Skip'}));renderImportReview()};
function saveImportReview(){let saved=0,skipped=0,failed=0;for(const c of importDraft){if(c.include===false){skipped++;continue}if(validateCandidate(c).length){failed++;continue}let type=c.equipmentType;if(!allEquipmentTypes().some(x=>x.toLowerCase()===type.toLowerCase()))type=saveCustomEquipment(type);if(!allTypes(c.primaryGroup).some(x=>x.toLowerCase()===c.primaryType.toLowerCase()))saveCustomMuscle(c.primaryGroup,c.primaryType);if(c.secondaryGroup&&c.secondaryType&&!allTypes(c.secondaryGroup).some(x=>x.toLowerCase()===c.secondaryType.toLowerCase()))saveCustomMuscle(c.secondaryGroup,c.secondaryType);let duplicate=library.find(e=>e.name.toLowerCase()===c.name.toLowerCase());if(duplicate){if(c.duplicateChoice==='Update Existing'){Object.assign(duplicate,{...c,equipmentType:type});saved++}else if(c.duplicateChoice==='Create New (Rename)'){library.push({id:uid(),...c,name:c.name.endsWith('Copy')?c.name:`${c.name} Copy`,equipmentType:type,...defaults(c.primaryGroup==='Cardio')});saved++}else skipped++}else{library.push({id:uid(),...c,equipmentType:type,...defaults(c.primaryGroup==='Cardio')});saved++}}
 persist();renderLibrary();importDraft=importDraft.filter(c=>c.include!==false&&validateCandidate(c).length);$p('importReviewDialog242').close();$p('exerciseImportDialog').close();$p('importResultsBody2421').innerHTML=`<div class="history-insights"><div class="history-stat"><b>${saved}</b><span>Saved</span></div><div class="history-stat"><b>${skipped}</b><span>Skipped</span></div><div class="history-stat"><b>${failed}</b><span>Need Attention</span></div></div>`;$p('importResults2421').showModal();if(importDraft.length)renderImportReview()}

function renderHistoryPatched(){const h=historyNewest(),tot=h.reduce((a,w)=>{const st=statsForExercises(w.exercises||[]);a.minutes+=Math.round((w.duration||0)/60000);a.sets+=st.sets;a.volume+=st.volume;return a},{minutes:0,sets:0,volume:0}),streak=computeWorkoutStreak();$p('historyInsights').innerHTML=`<div class="history-stat"><b>${h.length}</b><span>Workouts</span></div><div class="history-stat"><b>${tot.minutes}</b><span>Minutes</span></div><div class="history-stat"><b>${h.length?Math.round(tot.minutes/h.length):0}</b><span>Avg Min</span></div><div class="history-stat"><b>${streak.current}</b><span>Streak</span></div>`;$p('historyList').innerHTML=h.length?'':'<div class="card empty">No completed workouts yet.</div>';for(const w of h){const st=statsForExercises(w.exercises||[]),id=w.id||(w.id=uid());const d=document.createElement('div');d.className='card';d.innerHTML=`<div class="dashboard-strip"><div><b>${new Date(w.date).toLocaleDateString()}</b><div class="small muted">${Math.round((w.duration||0)/60000)} min · ${(w.exercises||[]).length} exercises · ${st.sets} sets · ${st.reps} reps · ${Math.round(st.volume).toLocaleString()} lb${st.cardio?` · ${st.cardio} cardio min`:''}${st.floors?` · ${st.floors} floors`:''}</div><div class="small">${esc((w.muscles||st.muscles).join(' · '))}${w.mood?` · Mood: ${esc(w.mood)}`:''}</div></div><button class="btn ghost" onclick="toggleHistory('${id}')">Details</button></div><div id="hist-${id}" class="history-details hidden"><pre class="summary-line">${esc(workoutSummary(w))}</pre><div class="history-actions"><button class="btn secondary" onclick="copyHistory('${id}')">Copy Summary</button><button class="btn secondary" onclick="saveHistoryPlan('${id}',false)">Save as Plan</button><button class="btn secondary" onclick="saveHistoryPlan('${id}',true)">Save as Favorite</button><button class="btn primary" onclick="repeatHistory('${id}')">Repeat Workout</button><button class="btn ghost" onclick="editHistoryNotes('${id}')">Edit Notes</button><button class="btn danger" onclick="deleteHistoryWorkout('${id}')">Delete Workout</button></div></div>`;$p('historyList').appendChild(d)}writeJSON('sw2_history',h)}
renderHistory=renderHistoryPatched;
window.editHistoryNotes=id=>{const h=getHistory(),w=h.find(x=>x.id===id);if(!w)return;const n=prompt('Edit overall workout notes:',w.notes||'');if(n===null)return;w.notes=n;writeJSON('sw2_history',h);queueCloudSync();renderHistory();renderDashboard()};
window.deleteHistoryWorkout=id=>{const h=getHistory(),w=h.find(x=>x.id===id);if(!w)return;if(!confirm(`Delete the workout from ${new Date(w.date).toLocaleDateString()}?`))return;writeJSON('sw2_history',h.filter(x=>x.id!==id));queueCloudSync();renderHistory();renderDashboard()};
window.copyHistory=id=>{const w=getHistory().find(x=>x.id===id);if(w)navigator.clipboard?.writeText(workoutSummary(w))};
window.repeatHistory=id=>{const w=getHistory().find(x=>x.id===id);if(w)repeatWorkout(w)};

renderDashboard=function(){let st=computeWorkoutStreak();$p('streakValue').textContent=`${st.current} Day${st.current===1?'':'s'} Strong`;$p('bestStreak').textContent=`Best streak: ${st.best} days`;$p('days').innerHTML=['M','T','W','T','F','S','S'].map((d,i)=>`<div class="day"><b>${d}</b><div class="dot ${st.week.has(i)?'done':''}">${st.week.has(i)?'✓':''}</div></div>`).join('');let h=historyNewest(),last=h[0];$p('lastWorkoutCard').innerHTML=last?`<div class="dashboard-strip"><div><div class="eyebrow">Last Workout</div><b>${new Date(last.date).toLocaleDateString()}</b><div class="meta">${Math.round((last.duration||0)/60000)} min · ${(last.exercises||[]).length} exercises</div><div class="small">${esc((last.muscles||statsForExercises(last.exercises||[]).muscles).join(' · '))}</div></div><button class="btn ghost" onclick="showPage('history')">View Summary →</button></div>`:`<div class="dashboard-strip"><div><div class="eyebrow">Last Workout</div><span class="muted">No completed workout yet</span></div></div>`;let done=exercises.filter(x=>x.done).length;$p('todayWorkoutCard').className='card today-dark';$p('todayWorkoutCard').innerHTML=`<div class="dashboard-strip"><div><div class="eyebrow accent">Today's Workout</div><b>${esc(localStorage.getItem('sw2_workout_title')||(exercises.length?'Workout in Progress':'Ready When You Are'))}</b><div class="meta">${done} of ${exercises.length} exercises completed</div><div class="progressbar"><span style="width:${exercises.length?done/exercises.length*100:0}%;background:var(--purple2)"></span></div></div><button class="btn primary" onclick="showPage('today')">${exercises.length?'Continue':'Build Workout'} →</button></div>`};

function reorderDashboard(){const dash=$p('dashboard');if(!dash)return;const streak=$p('streakValue')?.closest('.card'),today=$p('todayWorkoutCard'),last=$p('lastWorkoutCard'),quickTitle=dash.querySelector('.quick-title'),quick=dash.querySelector('.quick'),metrics=dash.querySelector('.metrics'),secondary=dash.querySelector('.two');if(streak&&today&&last){streak.after(today);today.after(last);if(quickTitle){last.after(quickTitle);if(quick)quickTitle.after(quick)}if(metrics){(quick||quickTitle||last).after(metrics)}if(secondary)metrics?.after(secondary)}dash.querySelectorAll('.metric').forEach(x=>x.classList.add('compact-metric'))}

function addStartOptions(){const hub=$p('buildHub');if(!hub)return;hub.innerHTML=`<div class="section-title">Start a Workout</div><div class="start-grid"><button class="btn primary" id="buildOwn2421">Build My Own</button><button class="btn secondary" id="suggest2421">Suggested or Random Workout</button><button class="btn secondary" id="paste2421">Paste Workout</button><button class="btn secondary" id="repeatPrevious2421">Repeat Previous</button><button class="btn secondary" id="saved2421">Saved Workouts</button><button class="btn secondary" id="favorites2421">Favorite Workouts</button></div>`;$p('buildOwn2421').onclick=()=>$p('addFromLibraryBtn').click();$p('suggest2421').onclick=()=>$p('randomWorkoutDialog').showModal();$p('paste2421').onclick=()=>$p('pasteWorkoutDialog').showModal();$p('repeatPrevious2421').onclick=repeatPrevious;$p('saved2421').onclick=()=>openPlanPicker(false);$p('favorites2421').onclick=()=>openPlanPicker(true)}

function addPatchUI(){
 if(!$p('importResults2421'))document.body.insertAdjacentHTML('beforeend','<dialog id="importResults2421"><div class="modal"><h2>Import Results</h2><div id="importResultsBody2421"></div><button class="btn primary full" onclick="importResults2421.close()">Done</button></div></dialog>');if(!$p('postSaveDialog'))document.body.insertAdjacentHTML('beforeend',`<dialog id="postSaveDialog"><div class="modal"><h2>Workout Saved</h2><p id="postSaveText"></p><div class="actions"><button class="btn primary" id="postViewHistory">View in History</button><button class="btn secondary" id="postHome">Return Home</button><button class="btn secondary" id="postRepeat">Repeat Workout</button><button class="btn ghost" id="postPlan">Save as Plan</button><button class="btn ghost" id="postFavorite">Save as Favorite</button></div></div></dialog>`);
 if(!$p('randomMuscles')){$p('randomCount').closest('.grid2').insertAdjacentHTML('afterend','<div class="field" style="margin-top:10px"><label>Custom Muscle Groups</label><select id="randomMuscles" multiple size="6"></select></div>');$p('randomFocus').insertAdjacentHTML('beforeend','<option>Custom</option>')}
 if(!$p('dashboardHelp2421')){const two=$p('dashboard')?.querySelector('.two');two?.insertAdjacentHTML('afterend','<div class="card help-card-dashboard" id="dashboardHelp2421"><img src="cova-wave.png" alt="Cova waving"><div><div class="eyebrow accent">Need Help?</div><p class="small">Cova is here to guide you every step.</p></div></div>')}
 $p('randomMuscles').innerHTML=allGroups().map(x=>`<option>${esc(x)}</option>`).join('');
}

function initFirebase(){
 const config={apiKey:'AIzaSyAUjzSaH6u61shEvXXYRAZaHwpMO9Ck6BY',authDomain:'sweat-and-stats.firebaseapp.com',projectId:'sweat-and-stats',storageBucket:'sweat-and-stats.firebasestorage.app',messagingSenderId:'577283178204',appId:'1:577283178204:web:ee642c6bc270bd65b17e19'};
 if(!window.firebase)return;try{const app=firebase.apps?.length?firebase.app():firebase.initializeApp(config);cloud.auth=app.auth();cloud.db=app.firestore();cloud.auth.setPersistence(firebase.auth.Auth.Persistence.LOCAL).catch(()=>{});createAuthUI();cloud.auth.onAuthStateChanged(user=>{cloud.user=user;if(user){hideAuth();$p('accountIdentity').textContent=`${user.displayName||'Sweat & Stats User'} · ${user.email||''}`;loadCloud()}else showAuth()})}catch(e){console.error(e)}
}
function createAuthUI(){if($p('authGate2421'))return;const settings=$p('settings');if(settings&&!$p('cloudPanel2421'))settings.insertAdjacentHTML('beforeend','<div class="card" id="cloudPanel2421"><h3>Account & Cloud Sync</h3><div id="cloudStatus2421" class="small muted">Signed out</div><button class="btn secondary" id="syncNow2421">Sync Now</button></div>');document.body.insertAdjacentHTML('beforeend',`<div id="authGate2421" class="auth-gate hidden"><div class="auth-card"><h1>Sweat & Stats</h1><div id="accountIdentity"></div><div class="field"><label>Name</label><input id="authName2421"></div><div class="field"><label>Email</label><input id="authEmail2421" type="email"></div><div class="field"><label>Password</label><input id="authPassword2421" type="password"></div><div id="authMessage2421" class="small"></div><div class="actions"><button class="btn primary" id="signIn2421">Sign In</button><button class="btn secondary" id="createAccount2421">Create Account</button><button class="btn ghost" id="forgot2421">Forgot Password</button><button class="btn ghost" id="offline2421">Continue Offline</button></div></div></div>`);$p('signIn2421').onclick=()=>authAction(false);$p('createAccount2421').onclick=()=>authAction(true);$p('forgot2421').onclick=async()=>{try{await cloud.auth.sendPasswordResetEmail($p('authEmail2421').value.trim());$p('authMessage2421').textContent='Password reset email sent.'}catch(e){$p('authMessage2421').textContent=e.message}};$p('offline2421').onclick=hideAuth;$p('signOut').onclick=()=>cloud.auth?.signOut();if($p('syncNow2421'))$p('syncNow2421').onclick=()=>syncCloudNow()}
function showAuth(){$p('authGate2421')?.classList.remove('hidden')}
function hideAuth(){$p('authGate2421')?.classList.add('hidden')}
async function authAction(create){try{const email=$p('authEmail2421').value.trim(),pass=$p('authPassword2421').value;let c=create?await cloud.auth.createUserWithEmailAndPassword(email,pass):await cloud.auth.signInWithEmailAndPassword(email,pass);if(create&&$p('authName2421').value.trim())await c.user.updateProfile({displayName:$p('authName2421').value.trim()})}catch(e){$p('authMessage2421').textContent=e.message}}
function localSnapshot(){const data={updatedAt:nowISO(),schemaVersion:SCHEMA};for(const k of CLOUD_KEYS){const v=localStorage.getItem(k);if(v!==null)data[k]=v}return data}
function setCloudStatus2421(t){if($p('cloudStatus2421'))$p('cloudStatus2421').textContent=t}
function mergeArrayById(local,remote){const m=new Map();for(const x of [...(local||[]),...(remote||[])]){const key=x.id||`${x.name||''}|${x.date||''}`;const prev=m.get(key);if(!prev||Date.parse(x.updatedAt||x.date||0)>=Date.parse(prev.updatedAt||prev.date||0))m.set(key,x)}return [...m.values()]}
async function syncCloudNow(){if(!cloud.user||!cloud.db)return alert('Sign in to sync.');setCloudStatus2421('Syncing…');await queueCloudSync(true);await loadCloud();setCloudStatus2421('Cloud connected')}
window.addEventListener('online',()=>{if(readJSON('sw2_sync_state',{}).status==='queued')queueCloudSync(true)});
async function loadCloud(){if(!cloud.user||!cloud.db)return;cloud.loading=true;try{const ref=cloud.db.collection('users').doc(cloud.user.uid).collection('app').doc('state'),doc=await ref.get();if(doc.exists){const remote=doc.data();const localTime=Date.parse(readJSON('sw2_sync_state',{}).updatedAt||0),remoteTime=Date.parse(remote.updatedAt||0);if(remoteTime>localTime){for(const k of CLOUD_KEYS){if(!Object.prototype.hasOwnProperty.call(remote,k))continue;if(['sw2_library','sw2_history','sw2_plans'].includes(k)){const local=readJSON(k,[]),r=(()=>{try{return JSON.parse(remote[k])}catch{return[]}})();writeJSON(k,mergeArrayById(local,r))}else if(!localStorage.getItem(k))localStorage.setItem(k,remote[k])}setCloudStatus2421('Cloud merged');location.reload();return}}else await ref.set(localSnapshot());writeJSON('sw2_sync_state',{updatedAt:nowISO(),status:'connected'})}catch(e){console.error(e);writeJSON('sw2_sync_state',{updatedAt:nowISO(),status:'offline',error:e.message})}finally{cloud.loading=false}}
function queueCloudSync(immediate=false){if(!cloud.user||!cloud.db||cloud.loading)return Promise.resolve();clearTimeout(cloud.timer);const run=async()=>{try{setCloudStatus2421('Saving…');await cloud.db.collection('users').doc(cloud.user.uid).collection('app').doc('state').set(localSnapshot(),{merge:true});writeJSON('sw2_sync_state',{updatedAt:nowISO(),status:'connected'});setCloudStatus2421('Cloud connected')}catch(e){writeJSON('sw2_sync_state',{updatedAt:nowISO(),status:'queued',error:e.message});setCloudStatus2421('Offline changes queued')}};if(immediate)return run();cloud.timer=setTimeout(run,800);return Promise.resolve()}
window.queueCloudSync=queueCloudSync;

function wire(){
 $p('finishBtn').onclick=openComplete;$p('completeBackBtn').onclick=()=>{showPage('today')};$p('completeCopyBtn').onclick=()=>navigator.clipboard?.writeText(workoutSummary({...completionRecord,notes:$p('completionNotes').value,mood:selectedMood}));$p('completeSaveBtn').onclick=finalSave;$p('saveBtn').onclick=openComplete;
 $p('loadPastedWorkoutBtn').onclick=()=>{const r=parseWorkoutTextPatched($p('pasteWorkoutText').value);if(!r.loaded.length)return alert('No library exercises were recognized.');if(!confirmReplace())return;exercises=r.loaded;localStorage.setItem('sw2_workout_title',r.title||'Pasted Workout');$p('workoutNotes').value=r.overall||'';persist();renderToday();$p('pasteWorkoutDialog').close();showPage('today')};
 $p('generateRandomBtn').onclick=balanceGenerate;$p('previewExerciseImportBtn').onclick=previewExerciseImports;$p('saveImport242').onclick=saveImportReview;$p('saveExerciseImportBtn').onclick=previewExerciseImports;
 $p('postViewHistory').onclick=()=>{$p('postSaveDialog').close();showPage('history')};$p('postHome').onclick=()=>{$p('postSaveDialog').close();showPage('dashboard')};$p('postRepeat').onclick=()=>{const w=getHistory().find(x=>x.id===$p('postSaveDialog').dataset.id);$p('postSaveDialog').close();if(w)repeatWorkout(w)};$p('postPlan').onclick=()=>{const w=getHistory().find(x=>x.id===$p('postSaveDialog').dataset.id);if(w){plans.push({id:uid(),name:w.title||'Saved Workout',favorite:false,exercises:w.exercises.map(x=>cleanToday(x,{preload:false}))});persist();renderPlans();alert('Saved as plan.')}};$p('postFavorite').onclick=()=>{const w=getHistory().find(x=>x.id===$p('postSaveDialog').dataset.id);if(w){plans.push({id:uid(),name:w.title||'Favorite Workout',favorite:true,exercises:w.exercises.map(x=>cleanToday(x,{preload:false}))});persist();renderPlans();alert('Saved as favorite.')}};
}

function patchVersion(){document.querySelectorAll('*').forEach(el=>{if(el.children.length===0&&el.textContent?.trim()==='v2.4.0.2')el.textContent='v2.4.0.2.1'});document.title='Sweat & Stats v2.4.0.2.1'}
function init(){migrate();addPatchUI();configureExerciseForm();addStartOptions();reorderDashboard();wire();patchVersion();renderToday();renderLibrary();renderPlans();renderHistory();renderDashboard();initFirebase()}
init();
})();
